debug: true

upload:
  path: G:\Users\sdm\IdeaProjects\vilkiwebApp\src\main\resources\pictures

spring:
  datasource:
    url: jdbc:postgresql://185.176.25.103/bkv_master_pg
    username: bkv_master_user_pg
    password: 8F9i5A3s
  jpa:
    generate-ddl: true